/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movieticketbookingsystem.gui;

import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import movieticketbookingsystem.Cinema;
import movieticketbookingsystem.Seat;

public class SeatChooser extends javax.swing.JFrame {

    private ImageIcon freeSeatIc, bookedSeatIc, selectedSeatIc;
    private Cinema cinema;
    private Seat selectedSeat;
    private JLabel[][] labels; // grid labels
    private int rows, seatsInEachRow;

    private static SeatChooser instance = new SeatChooser();

    /**
     * Creates new form SeatChooser
     */
    public SeatChooser() {
        initComponents();
        freeSeatIc = new ImageIcon("Resources/Icons/free_seat.png");
        bookedSeatIc = new ImageIcon("Resources/Icons/booked_seat.png");
        selectedSeatIc = new ImageIcon("Resources/Icons/selected_seat.png");
    }

    public static SeatChooser getInstance() {
        return instance;
    }

    public JLabel getLabel(int r, int c) {
        return labels[r][c];
    }

    public void setSeatBooked(Seat seat, boolean book) {
        Image image = null;
        if (book) {
            image = selectedSeatIc.getImage();
            selectedSeat = seat;
        } else {
            image = freeSeatIc.getImage();
        }
        ImageIcon imageIcon = new ImageIcon(image);
        getLabel(seat.getRowNumber() - 1, seat.getSeatNumber() - 1)
                .setIcon(imageIcon);
        seatsPanel.repaint();
    }
    
    private void updateFreeSeatsNotification() {
        this.freeseatNotification.setText("Free Seats : " + cinema.getFreeSeats());
    }

    public void showInterface(Cinema cinema, Seat selected) {
        this.cinema = cinema;

        rows = cinema.getRowCount();
        seatsInEachRow = cinema.getRowSeatsCount();

        this.labels = new JLabel[rows][seatsInEachRow];

        // clean the grid
        seatsPanel.removeAll();

        selectedSeat = selected;

        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < seatsInEachRow; j++) {

                Seat seat = cinema.getSeat(i + 1, j + 1);
                JLabel label = new JLabel();
                Image image = null;
                if (seat.isIsReserved()) {
                    image = bookedSeatIc.getImage();
                } else {
                    image = freeSeatIc.getImage();
                    if (seat.equals(selectedSeat)) {
                        image = selectedSeatIc.getImage();
                    }
                    label.addMouseListener(new MouseAdapter() {

                        @Override
                        public void mouseClicked(MouseEvent e) {
                            if (selectedSeat == null) {
                                setSeatBooked(seat, true);
                            } else {
                                setSeatBooked(selectedSeat, false);
                                setSeatBooked(seat, true);
                            }
                            updateFreeSeatsNotification();
                        }

                    });
                }
                label.setIcon(new ImageIcon(image));
                labels[i][j] = label;
                seatsPanel.add(label);
            }
        }

        seatsPanel.setLayout(new GridLayout(rows, seatsInEachRow));

        instance.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                instance.dispose();
            }

        });
        instance.setVisible(true);
        updateFreeSeatsNotification();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        seatsPanel = new javax.swing.JPanel();
        reserveBtn = new javax.swing.JButton();
        freeseatNotification = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jButtonBack.setText("<< Back");
        jButtonBack.setFocusPainted(false);
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reserve Your Seat");

        javax.swing.GroupLayout seatsPanelLayout = new javax.swing.GroupLayout(seatsPanel);
        seatsPanel.setLayout(seatsPanelLayout);
        seatsPanelLayout.setHorizontalGroup(
            seatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        seatsPanelLayout.setVerticalGroup(
            seatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        reserveBtn.setText("Reserve");
        reserveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveBtnActionPerformed(evt);
            }
        });

        freeseatNotification.setText("Free Seats :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(seatsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBack)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 166, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reserveBtn)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(freeseatNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(freeseatNotification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reserveBtn)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        instance.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void reserveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveBtnActionPerformed
        if (selectedSeat == null) {
            JOptionPane.showMessageDialog(this, "Please select a seat to reserve!");
            return;
        }
        MakeBookingPanel.getInstance().setSelectedSeat(selectedSeat);
        instance.dispose();
    }//GEN-LAST:event_reserveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel freeseatNotification;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reserveBtn;
    private javax.swing.JPanel seatsPanel;
    // End of variables declaration//GEN-END:variables
}
